### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by rakanalh** [videlalvaro/php-amqplib#146]
Hello,

I am trying to publish a message to rabbitmq as follows:
```php
$this->connection = new AMQPConnection('127.0.0.1', '5672', 'myuser','mypassword', 'myvhost');

$this->channel = $this->connection->channel();

$this->message = new AMQPMessage('', array('delivery_mode' => 2));

try {
            $this->message->setBody(json_encode($event));
            $this->channel->basic_publish($this->message, 'amq.direct', 'exchangename');
        }
        catch(Exception $e) {
            var_dump($event);
            print $e->getTraceAsString();
        }

```

Here's the dump of the array i am trying to publish:
```
array(4) {
  ["timestamp"]=>
  string(25) "2014-01-30T09:37:52+00:00"
  ["message"]=>
  string(11) "Rabbit 1764"
  ["priority"]=>
  int(3)
  ["priorityName"]=>
  string(3) "ERR"
}
```

1 message succeeds, 1000 messages succeed. However, going over that number, the library starts firing exceptions as follows:

```
PHP Notice:  fwrite(): send of 134 bytes failed with errno=11 Resource temporarily unavailable in /home/vagrant/Work/Logger/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 65

#0 /home/vagrant/Work/Logger/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(174): PhpAmqpLib\Wire\IO\StreamIO->write('????????<?(???a...')
#1 /home/vagrant/Work/Logger/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(203): PhpAmqpLib\Connection\AbstractConnection->write('????????<?(???a...')
#2 /home/vagrant/Work/Logger/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php(803): PhpAmqpLib\Connection\AbstractConnection->send_content(1, 60, 0, 99, '???', '{"timestamp":"2...', Object(PhpAmqpLib\Wire\AMQPWriter))
#3 /home/vagrant/Work/Logger/libs/App/Log/Writer/RabbitMQ.php(62): PhpAmqpLib\Channel\AMQPChannel->basic_publish(Object(PhpAmqpLib\Message\AMQPMessage), 'amq.direct', 'exchangename')
#4 /home/vagrant/Work/Logger/libs/Zend/Log/Writer/Abstract.php(80): App_Log_Writer_RabbitMQ->_write(Array)
#5 /home/vagrant/Work/Logger/libs/Zend/Log.php(157): Zend_Log_Writer_Abstract->write(Array)
#6 /home/vagrant/Work/Logger/testRabbit.php(24): Zend_Log->log('Rabbit 1764', 3)
#7 {main}
```

Please advise.

**Comment by marcofranssen** [comment]
Having the same issue currently. 

using `videlalvaro/php-amqplib": "2.2.*`

Doing a pub sub with three listener processes. It fails in less than a minute when using `--batch` and `--loop` mode like this.

First start three listereners (see connect lines in the rabbitmq log)
Then start the publisher...

How to deal with this issue?

### Code publishing
```php
<?php

namespace Bluekiwi\Commands;

use Bluekiwi\Config;
use Bluekiwi\Factories\RabbitFactory;
use PhpAmqpLib\Connection\AmqpConnection;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SendCommand extends Command
{
    private $channel;
    private $rabbitFactory;

    protected function configure()
    {
        $this->setName('send')
             ->setDescription('Send a chatmessage')
             ->addArgument('message', InputArgument::OPTIONAL, 'What message do you want to send?', 'Hello World!')
             ->addOption('batch', 'b', InputOption::VALUE_REQUIRED, 'Path to your inputfile')
             ->addOption('yell', null, InputOption::VALUE_NONE, 'If set your message will be in uppercase letters.')
             ->addOption('loop', null, InputOption::VALUE_NONE, 'If set your messages will be sent in a loop.')
             ->addOption('silent', 's', InputOption::VALUE_NONE, 'No output of the messages being sent.');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $config = new Config();
        $connection = new AMQPConnection($config->host, $config->port, $config->user, $config->password, $config->vhost);
        $this->channel = $connection->channel();

        $exchange = 'chats';

        $this->rabbitFactory = new RabbitFactory($this->channel);
        $this->channel->exchange_declare($exchange, 'fanout', false, false, true);

        $messages = [];
        if ($input->getOption('batch')) {
            $filePath = $input->getOption('batch');
            $messages = $this->readFile($filePath);
        } else {
            $messages[] = $input->getArgument('message');
        }

        if ($input->getOption('loop')) {
            $output->writeLn(' [*] Sending messages. To exit press CTRL+C');
            while (true) {
                $this->sendMessages($messages, $exchange, $output, $input->getOption('yell'), $input->getOption('silent'));
            }
        } else {
            $this->sendMessages($messages, $exchange, $output, $input->getOption('yell'), $input->getOption('silent'));
        }

        $this->channel->close();
        $connection->close();
    }

    private function sendMessages($messages, $exchange, $output, $yell = false, $silent = true)
    {
        foreach ($messages as &$message) {
            if ($yell) {
                $message = strtoupper($message);
            }

            try {
                $this->publishMessage($message, $exchange);
            } catch(Exception $e) {
                var_dump($event);
                print $e->getTraceAsString();
            }
            
            if (!$silent) {
                $output->writeLn(' [x] Sent: ' . $message);
            }
        }
        unset($message);
    }

    private function readFile($filePath)
    {
        $messages = [];
        $handle = fopen($filePath, "r");
        if ($handle) {
            while (($line = fgets($handle)) !== false) {
                $messages[] = $line;
            }

            fclose($handle);
        } else {
            // error opening the file.
        }
        return $messages;
    }

    private function publishMessage($data, $exchange)
    {
        $msg = $this->rabbitFactory->createTextMessage($data);
        $this->channel->basic_publish($msg, $exchange);
    }
}
```

### PHP error
```shell
PHP Notice:  fwrite(): send of 18 bytes failed with errno=11 Resource temporarily unavailable in /srv/rabbitmq-test-app/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 65
```

### The logs
```bash
=INFO REPORT==== 12-May-2015::12:27:54 ===
Starting RabbitMQ 3.5.1 on Erlang R15B01
Copyright (C) 2007-2014 GoPivotal, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 12-May-2015::12:27:54 ===
node           : rabbit@bk-dev-mfr
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : vHiZIFLi4WwXgOOPek6lzQ==
log            : /var/log/rabbitmq/rabbit@bk-dev-mfr.log
sasl log       : /var/log/rabbitmq/rabbit@bk-dev-mfr-sasl.log
database dir   : /var/lib/rabbitmq/mnesia/rabbit@bk-dev-mfr

=INFO REPORT==== 12-May-2015::12:27:54 ===
Limiting to approx 924 file handles (829 sockets)

=INFO REPORT==== 12-May-2015::12:27:54 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 12-May-2015::12:27:54 ===
Memory limit set to 1006MB of 2012MB total.

=INFO REPORT==== 12-May-2015::12:27:54 ===
Disk free limit set to 50MB

=INFO REPORT==== 12-May-2015::12:27:54 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 12-May-2015::12:27:54 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 12-May-2015::12:27:54 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 12-May-2015::12:27:54 ===
Management plugin started. Port: 15672

=INFO REPORT==== 12-May-2015::12:27:54 ===
Statistics database started.

=INFO REPORT==== 12-May-2015::12:27:54 ===
Server startup complete; 6 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * webmachine
 * mochiweb
 * rabbitmq_management_agent
 * amqp_client

=INFO REPORT==== 12-May-2015::12:32:51 ===
accepting AMQP connection <0.442.0> ([::1]:37791 -> [::1]:5672)

=INFO REPORT==== 12-May-2015::12:32:53 ===
accepting AMQP connection <0.463.0> ([::1]:37792 -> [::1]:5672)

=INFO REPORT==== 12-May-2015::12:32:55 ===
accepting AMQP connection <0.482.0> ([::1]:37793 -> [::1]:5672)

=INFO REPORT==== 12-May-2015::12:33:03 ===
accepting AMQP connection <0.504.0> ([::1]:37794 -> [::1]:5672)

=ERROR REPORT==== 12-May-2015::12:33:37 ===
Error on AMQP connection <0.504.0> ([::1]:37794 -> [::1]:5672, vhost: 'chat', user: 'chat', state: running), channel 1:
{amqp_error,frame_error,
            "type 3, all octets = <<0>>: {invalid_frame_end_marker,0}",none}

=ERROR REPORT==== 12-May-2015::12:33:40 ===
closing AMQP connection <0.504.0> ([::1]:37794 -> [::1]:5672):
fatal_frame_error
```
